name: Weekly LINE Notify Message Test

on:
  schedule:
    - cron: '*/4 * * * *'

jobs:
  send-message:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Or the Python version you need
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
        
      - name: Run Python script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Make sure to set this in GitHub secrets
        run: |
          python line_church_bento_notify.py  # Full path for clarity

          
